- name: Create kubernetes components folder
  file:
    path: '/tmp/components/{{ kube_components_item }}'
    state: 'directory'

- name: Kubernetes components manifest file transfer
  template:
    src: 'components/{{ kube_components_item }}/{{ item | basename }}'
    dest: '/tmp/components/{{ kube_components_item }}/{{ item | basename }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ lookup('fileglob', '../templates/components/{{ kube_components_item }}/*.yaml', wantlist=True) }}"

- name: Apply the components manifest
  command: 'kubectl create -f /tmp/components/{{ kube_components_item }}'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  changed_when: false
  failed_when: false

- name: Remove kubernetes components folder
  file:
    path: '/tmp/components'
    state: 'absent'
  when: kube_template_clean | bool
