---
- name: Remove swapfile from /etc/fstab.
  mount:
    path: '{{ item }}'
    fstype: 'swap'
    state: 'absent'
  loop:
    - 'none'
    - 'swap'
  changed_when: false
  failed_when: false

- name: Disable swap.
  command: 'swapoff -a'
  when: ansible_swaptotal_mb > 0

- name: Installs necessary runtime module.
  modprobe:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ kube_module_dependent }}'
  changed_when: false
  failed_when: false

- name: Dependents runtime module loaded file transfer.
  template:
    src: 'crio.conf.j2'
    dest: '/etc/modules-load.d/crio.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure kernel parameters.
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: '{{ kube_kernel_parameters }}'
  when: item.create | default(true) | bool

#- name: Create kubelet files root directory.
#  file:
#    path: '{{ kube_cri.path }}/kubelet'
#    state: 'directory'
#    owner: 'root'
#    group: 'root'
#    mode: '0711'
#  when: kube_cri.path is defined