---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Kubernetes firewalld operation
  block:
    - name: Allow Kubernetes service port
      firewalld:
        port: '{{ item.value }}/tcp'
        zone: 'public'
        permanent: 'yes'
        state: 'enabled'
      loop: '{{ kube_port_arg | dict2items }}'
    - name: Enable IP masquerading
      firewalld:
        masquerade: 'yes'
        state: 'enabled'
        permanent: 'yes'
        zone: 'public'
    - name: Allow default interface traffic 
      shell: 'firewall-cmd --permanent --direct --add-rule ipv4 filter {{ item }} 1 -j ACCEPT'
      with_items:
        - 'INPUT'
        - 'FORWARD'
        - 'OUTPUT'
      register: kube_firewalld_status
    - name: Reload firewalld service
      systemd:
        name: 'firewalld.service'
        enabled: 'yes'
        state: 'restarted'
        daemon_reload: 'yes'
      when: kube_firewalld_status is changed
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
