---
- name: Create kubernetes fluentd-elasticsearch folder.
  file:
    path: '/tmp/fluentd-elasticsearch'
    state: 'directory'

- name: Kubernetes fluentd-elasticsearch manifest file transfer.
  template:
    src: 'fluentd-elasticsearch/{{ item | basename }}'
    dest: '/tmp/fluentd-elasticsearch/{{ item | basename }}'
    variable_start_string: "<<"
    variable_end_string: ">>"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ lookup('fileglob', '../templates/fluentd-elasticsearch/*.yaml', wantlist=True) }}"

- name: Apply the fluentd-elasticsearch manifest.
  command: 'kubectl create -f /tmp/fluentd-elasticsearch'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  changed_when: false
  failed_when: false

- name: Remove kubernetes fluentd-elasticsearch folder.
  file:
    path: '/tmp/fluentd-elasticsearch'
    state: 'absent'
  when: kube_template_clean | bool
