- name: Create kubernetes fluentd-gelf folder
  file:
    path: '/tmp/fluentd-gelf'
    state: 'directory'

- name: Kubernetes fluentd-gelf manifest file transfer
  template:
    src: 'fluentd-gelf/{{ item | basename }}'
    dest: '/tmp/fluentd-gelf/{{ item | basename }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ lookup('fileglob', '../templates/fluentd-gelf/*.yaml', wantlist=True) }}"

- name: Apply the fluentd-gelf manifest
  command: 'kubectl create -f /tmp/fluentd-gelf'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  changed_when: false
  failed_when: false

- name: Remove kubernetes fluentd-gelf folder
  file:
    path: '/tmp/fluentd-gelf'
    state: 'absent'
  when: kube_template_clean | bool
