---
- name: Create kubernetes fluentbit-gelf folder.
  file:
    path: '/tmp/fluentbit-gelf'
    state: 'directory'

- name: Kubernetes fluentbit-gelf manifest file transfer.
  template:
    src: 'fluentbit-gelf/{{ item | basename }}'
    dest: '/tmp/fluentbit-gelf/{{ item | basename }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ lookup('fileglob', '../templates/fluentbit-gelf/*.yaml', wantlist=True) }}"

- name: Apply the fluentbit-gelf manifest.
  command: 'kubectl create -f /tmp/fluentbit-gelf'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  changed_when: false
  failed_when: false

- name: Remove kubernetes fluentbit-gelf folder.
  file:
    path: '/tmp/fluentbit-gelf'
    state: 'absent'
  when: kube_template_clean | bool
