---
- name: Get kubernetes control plane containers image list.
  shell: "/bin/kubeadm config images list --kubernetes-version=v1.23.12 | awk -F '/' '{print $NF}'"
  register: kube_control_plane_image_list

- name: Pull an kubernetes control plane containers image.
  shell: "crictl -r /run/containerd/containerd.sock pull registry.aliyuncs.com/google_containers/{{ item }}"
  loop: '{{ kube_control_plane_image_list.stdout_lines }}'
  register: kube_image_pull_status
  until: kube_image_pull_status is succeeded
  retries: 5
  delay: 2