---
- name: Check local consul client are accessible from current host
  uri:
    url: '{{ consul_public_http_prot }}://{{ ansible_default_ipv4.address }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'GET'
    timeout: '5'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  changed_when: false
  failed_when: false
  register: check_consul_local

- name: Register service with an http health check
  uri:
    url: '{{ consul_public_http_prot }}://{{ ansible_default_ipv4.address }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["kubernetes"],"ID":"{{ group_names[-1] | upper | regex_replace("_", "-") }}-{{ environments | upper | regex_replace("_", "-") }}-APIServer","name":"{{ group_names[-1] | upper | regex_replace("_", "-") }}-{{ environments | upper | regex_replace("_", "-") }}-APIServer","address":"{{ ansible_default_ipv4.address }}","port":{{ kube_port_arg.api_server }},"checks":[{"tcp":"{{ ansible_default_ipv4.address }}:{{ kube_port_arg.api_server }}","interval":"10s","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  when: check_consul_local.status == 405
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false

- name: Kubeadm confuration file transfer
  template:
    src: 'kubeadm-config.yaml.j2'
    dest: '/tmp/kubeadm-config.yaml'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Initialize Kubernetes master
  command: >
    kubeadm init
    --config=/tmp/kubeadm-config.yaml
    --{% if kube_version.split('.')[0] == '1' and kube_version.split('.')[1] == '14' %}experimental-upload-certs{% else %}upload-certs{% endif %}
    --ignore-preflight-errors=all
  environment:
    no_proxy: '*'
