---
- name: Initialize Kubernetes master
  command: >
    kubeadm init
    --image-repository {{ kube_registry_server | default('gcr.azk8s.cn/google_containers') }}
    --pod-network-cidr={{ kube_network.pod_cidr | default('10.244.0.0/16') }}
    --service-cidr={{ kube_network.srv_cidr | default('10.96.0.0/12') }}
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --kubernetes-version v{{ kube_version | default('1.15.2') }}
    --ignore-preflight-errors=Swap
    --ignore-preflight-errors=NumCPU
  failed_when: false
  when: not kube_init_stat.stat.exists

- name: Ensure .kube directory exists
  file:
    path: '{{ ansible_env.PWD }}/.kube'
    state: 'directory'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Symlink the kubectl admin.conf
  copy:
    src: '/etc/kubernetes/admin.conf'
    dest: '{{ ansible_env.PWD }}/.kube/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
    remote_src: 'yes'
