---
- name: Join to Kubernetes control plane.
  shell: >
    {{ kube_plan_join_command }}
    --node-name {{ ansible_nodename | lower }}
    creates=/etc/kubernetes/kubelet.conf
  environment:
    no_proxy: '*'
  notify: 'Kubernetes control plane node labele applied'
  register: kube_join_status
  until: kube_join_status is succeeded
  retries: 3
  delay: 5

- name: Check local consul client are accessible from current host.
  uri:
    url: '{{ consul_public_http_prot }}://{{ ansible_default_ipv4.address }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'GET'
    timeout: '5'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  changed_when: false
  failed_when: false
  register: check_consul_local

- name: Register service with an health check.
  uri:
    url: '{{ consul_public_http_prot }}://{{ ansible_default_ipv4.address }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["kubernetes"],"ID":"{{ customer | lower | regex_replace("_", "-") }}-{{ environments | lower | regex_replace("_", "-") }}-{{ group_names[-1] | lower | regex_replace("_", "-") }}-{{ group_names[0] | lower | regex_replace("_", "-") }}-apiserver","name":"{{ customer | lower | regex_replace("_", "-") }}-{{ environments | lower | regex_replace("_", "-") }}-{{ group_names[-1] | lower | regex_replace("_", "-") }}-{{ group_names[0] | lower | regex_replace("_", "-") }}-apiserver","address":"{{ ansible_default_ipv4.address }}","port":{{ kube_port_tcp_arg.api }},"checks":[{"tcp":"{{ ansible_default_ipv4.address }}:{{ kube_port_tcp_arg.api }}","interval":"10s","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  when: check_consul_local.status == 405
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false

- name: Kube controller manager extra args configuration.
  lineinfile:
    state: 'present'
    dest: '/etc/kubernetes/manifests/kube-controller-manager.yaml'
    insertafter: '    - kube-controller-manager'
    regexp: '    - --{{ item }}'
    line: '    - --{{ item }}'
  loop: '{{ kube_controller_manager_extra_args }}'