---
- name: Kubernetes networking cni manifest transfer
  template:
    src: '{{ kube_network.cni }}.yaml.j2'
    dest: '/tmp/{{ kube_network.cni }}.yaml'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Apply the {{ kube_network.cni }} networking manifest'
  command: 'kubectl apply -f "/tmp/{{ kube_network.cni }}.yaml"'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
