---
- name: Join node to Kubernetes master
  shell: >
    {{ kube_node_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  environment:
    no_proxy: '*'
  register: kube_join_status
  until: kube_join_status is succeeded
  retries: 3
  delay: 5
