---
- name: Join node to Kubernetes master
  shell: >
    {{ kube_node_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  environment:
    no_proxy: '*'
  register: kube_join_status
  until: kube_join_status is succeeded
  retries: 3
  delay: 5

- name: Kubernetes node labele applied
  command: 'kubectl label nodes {{ ansible_fqdn | lower }} --overwrite environment="{{ environments | default("Development") | upper }}" group="{{ group_names[0] | default ("") | upper }}" nodeType="slave"'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/kubelet.conf'
