---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution_file_variety }}.yml'

- name: Add EPEL YUM repositories.
  yum_repository:
    name: '{{ kube_epel_repo_name }}'
    description: '{{ kube_epel_repo_name }} YUM repo'
    file: '{{ kube_epel_repo_name }}'
    baseurl: '{{ kube_epel_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'
  when:
    - kube_backupset_arg.cloud_rsync | bool
    - kube_backupset_arg.cloud_drive is defined
    - kube_node_role == 'master'

- name: Install the Rclone command line program packages.
  yum:
    name: 'rclone'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
    update_cache: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
  when:
    - kube_backupset_arg.cloud_rsync | bool
    - kube_backupset_arg.cloud_drive is defined
    - kube_node_role == 'master'

- name: Add Kubernetes YUM repositories.
  yum_repository:
    name: '{{ kube_repo_name }}'
    description: '{{ kube_repo_name }} YUM repository'
    file: '{{ kube_repo_name }}'
    baseurl: '{{ kube_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the Kubernetes packages.
  yum:
    name: '{{ kube_package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: kube_soft_update
  until: kube_soft_update is succeeded
  retries: 5
  delay: 2

- name: kubelet services file transfer.
  template:
    src: 'kubelet.j2'
    dest: '/etc/sysconfig/kubelet'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: kube_conf_update
