---
- name: Add Kubernetes YUM repositories
  yum_repository:
    name: '{{ kube_repo_name }}'
    description: '{{ kube_repo_name }} YUM repository'
    file: '{{ kube_repo_name }}'
    baseurl: '{{ kube_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Kubernetes packages
  yum:
    name: '{{ kube_package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: kube_soft_update
  until: kube_soft_update is succeeded
  retries: 3
  delay: 5

- name: kubelet services file transfer
  template:
    src: 'kubelet.j2'
    dest: '/etc/sysconfig/kubelet'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: kube_conf_update
