---
- include: 'RedHat.yml'
  when: ansible_os_family == 'RedHat'

- name: Kubernetes control plane node labele applied
  command: 'kubectl label nodes {{ ansible_fqdn | lower }} --overwrite datacenter="{{ datacenter | default("dc01") | lower }}" domain="{{ domain | default("local") | lower }}" environment="{{ environments | default("prd") | lower }}" project="{{ group_names[-1] | title | regex_replace("_", "-") }}" group="{{ group_names[0] | title | regex_replace("_", "-") }}" application="Platform" customer="{{ customer | title | regex_replace("_", "-") }}" nodeType="master"'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'
