---
- name: Kubernetes control plane node labele applied
  command: 'kubectl label nodes {{ ansible_fqdn | lower }} --overwrite datacenter="{{ datacenter | default("dc01") | lower }}" domain="{{ domain | default("local") | lower }}" environment="{{ environments | default("prd") | lower }}" project="{{ group_names[-1] | title | regex_replace("_", "-") }}" group="{{ group_names[0] | title | regex_replace("_", "-") }}" customer="{{ customer | title | regex_replace("_", "-") }}"{% if kube_node_extra_labels is defined %} {{ " ".join(vars["kube_node_extra_labels"]) }}{% endif %}'
  environment:
    no_proxy: '*'
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- name: Enable kubernetes service
  systemd:
    name: 'kubelet.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  listen: Ensure kubelet service is enabled

- name: Reloading the Containerd service
  systemd:
    name: 'containerd.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  listen: Ensure Containerd service is enabled
