apiVersion: v1
data:
  GELF_HOST: {{ kube_fluentd_gelf_host | default('127.0.0.1') }}
  GELF_PORT: "{{ kube_fluentd_gelf_port | default('12201') }}"
  GELF_PROTOCOL: {{ kube_fluentd_gelf_protocol | default('udp') }}
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>

    <source>
      @type systemd
      tag systemd
      path /var/log/journal
      <storage>
        @type local
        persistent true
        path /pos
      </storage>
      <entry>
        field_map '{"MESSAGE": "log", "_PID": ["process", "pid"], "_CMDLINE": "process", "_COMM": "cmd"}'
        fields_strip_underscores true
        fields_lowercase true
      </entry>
      read_from_head true
    </source>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /pos/containers.pos
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
    </filter>

    <filter access>
      @type record_transformer
      <record>
        hostname "#{ENV['NODENAME']}"
      </record>
    </filter>

    <filter **>
     @type record_modifier
     char_encoding utf-8
    </filter>

    <match **>
       @type copy
       <store>
         @type gelf
         include_tag_key true
         host "#{ENV['GELF_HOST']}"
         port "#{ENV['GELF_PORT']}"
         protocol "#{ENV['GELF_PROTOCOL']}"
         # tls <true or false>
         # tls_options {}
         # Supported tls_options:
         # 'no_default_ca' [Boolean] prevents OpenSSL from using the systems CA store.
         # 'tls_version' [Symbol] any of :TLSv1, :TLSv1_1, :TLSv1_2 (default)
         # 'cert' [String, IO] the client certificate file
         # 'key' [String, IO] the key for the client certificate
         # 'all_ciphers' [Boolean] allows any ciphers to be used, may be insecure
         <buffer>
           flush_at_shutdown true
           flush_mode interval
           flush_thread_count 4
           flush_thread_interval 1
           flush_thread_burst_interval 1
           retry_forever false
           retry_max_times 3
           retry_type exponential_backoff
         </buffer>
         use_record_host true
       </store>
    </match>

    # Valid log_level's are: fatal, error, warn, info, debug, trace
    <system>
      log_level warn
    </system>
kind: ConfigMap
metadata:
  name: kube-gelf
  namespace: kube-system
